name: {{cookiecutter.project_name}} 
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - matplotlib
  - scikit-learn
  # for development only (could also be kept in a separate environment file)
  - jupyterlab
  - sphinx
  - recommonmark
